use crate::background::models::now_ms;

/// Priority level for an `AdaptiveEvent`.
/// Higher priority events drain first from the `EventQueue`.
/// Within the same priority level, events are processed FIFO.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum EventPriority {
    /// Critical events always process first.
    /// Never deduplicated. Never dropped.
    /// Examples: WakeFromSleep, DisplayRemoved.
    Critical = 3,

    /// High priority. Process before Normal.
    /// May be deduplicated with consecutive identical events.
    /// Examples: ProfileUpdated, ConfigurationChanged.
    High = 2,

    /// Standard priority. Process in turn.
    /// Deduplicated aggressively.
    /// Examples: ScreenContentChanged, AmbientChanged.
    Normal = 1,

    /// Background tick. Lowest priority.
    /// Always deduplicated — only one `PeriodicTick` enqueued at a time.
    Low = 0,
}

/// The type of event triggering an adaptive pipeline cycle.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AdaptiveEventKind {
    // ── Active Event Sources ─────────────────────────────────────
    /// Screen content luminance has shifted beyond threshold.
    ScreenContentChanged,
    /// Ambient light reading has shifted beyond threshold.
    AmbientChanged,
    /// User's comfort profile was created, updated, or deleted.
    ProfileChanged,
    /// Application configuration was saved.
    ConfigurationChanged,
    /// OS reported a wake-from-sleep event.
    WakeFromSleep,
    /// OS reported a sleep or hibernate event.
    SleepSignal,
    /// A display was connected at runtime.
    DisplayConnected,
    /// A display was disconnected at runtime.
    DisplayRemoved,
    /// Manual trigger (e.g., user presses "Refresh" in UI).
    Manual,
    /// Periodic background tick — generated by PollingScheduler.
    PeriodicTick,

    // ── Future Event Sources (documented, not implemented) ────────
    /// Native display change notifications (WM_DISPLAYCHANGE).
    /// Future: replaces startup-only display discovery.
    // FutureNativeDisplayNotification,

    /// Ambient sensor hardware interrupt (zero-polling mode).
    /// Future: eliminates the need for periodic ambient polling.
    // FutureAmbientSensorInterrupt,

    /// Window focus change (foreground application changed).
    /// Future: enables per-app comfort profiles.
    // FutureWindowFocusChange,

    /// GPU performance counter notification (frame time change).
    /// Future: enables GPU-triggered luminance analysis.
    // FutureGpuNotification,

    /// OS power plan change notification.
    /// Future: activates PowerMode switching.
    // FuturePowerPlanChange,
}

/// A single event in the adaptive event pipeline.
#[derive(Debug, Clone)]
pub struct AdaptiveEvent {
    pub kind: AdaptiveEventKind,
    pub priority: EventPriority,
    /// The display this event is scoped to, if any.
    pub display_id: Option<String>,
    /// UNIX timestamp in milliseconds when this event was created.
    pub timestamp_ms: u64,
}

impl AdaptiveEvent {
    pub fn new(kind: AdaptiveEventKind, priority: EventPriority) -> Self {
        Self {
            kind,
            priority,
            display_id: None,
            timestamp_ms: now_ms(),
        }
    }

    pub fn for_display(kind: AdaptiveEventKind, priority: EventPriority, display_id: &str) -> Self {
        Self {
            kind,
            priority,
            display_id: Some(display_id.to_string()),
            timestamp_ms: now_ms(),
        }
    }

    /// Returns true if this event kind can be deduplicated with consecutive identical events.
    /// Critical events are never deduplicated.
    pub fn is_deduplicable(&self) -> bool {
        !matches!(
            self.priority,
            EventPriority::Critical
        )
    }
}
