name: Question
description: Ask a question about PixelSense
labels: ["help wanted"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
