name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  validate_code:
    name: Code Validation
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Check Formatting
      run: cargo fmt -- --check
      
    - name: Clippy Lints
      run: cargo clippy -- -D warnings
      
    - name: Run Tests
      run: cargo test
